[package]
name = "tinysys_sys"
version = "0.1.0"
edition = "2024"

[features]
default = []
# default = ["bindgen"]
std = []

[dependencies]

[build-dependencies]
bindgen = { version = "0.71", optional = true }
