[target.riscv32im-unknown-none-elf]
# runner = "riscv64-unknown-elf-gdb -q -x gdb_init"
rustflags = [
    # "-C", "target-feature=+zicsr,+zifencei,+zfinx",
]

[build]
target = "riscv32im-unknown-none-elf"
